// hello-world/read-video-react/src/components/ImgNormalizer/ImgNormalizer.js
import React, { Component } from 'react';
import { DocumentNormalizer } from "@scannerproxy/ddnjs";
import './ImgNormalizer.css'

export default class ImgNormalizer extends Component {
  constructor(props) {
    super(props);
    this.pNormaelizer = null;
    this.elInr = React.createRef();
  }

  normalizeImg = async (e) => {
    try {
      const normalizer = await (this.pNormaelizer = this.pNormaelizer || DocumentNormalizer.createInstance());
      let results = await normalizer.detectQuad(e.target.files[0]);
      this.elInr.current.innerHTML = "";
      for(let item of results) {
        const norRes = await normalizer.normalize(e.target.files[0], {quad: item.location});
        const cvs = norRes.image.toCanvas();
        if(document.body.clientWidth < 600) {
          cvs.style.width = "100%";
        }
        this.elInr.current.appendChild(cvs);
      }
      console.log(results);
    } catch(ex) {
      let errMsg;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message||ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
    e.target.value = '';
  }

  async componentWillUnmount() {
    if (this.pNormalizer) {
      (await this.pNormalizer).dispose();
      this.pNormalizer = null;
      console.log('ImgNormalizer Component Unmount');
    }
  }

  render() {
    return (
      <div>
        <div className="ImgNormalizer"><input type="file" onChange={this.normalizeImg}/></div>
        <div className="img-normalized-result" ref={this.elInr}></div>
      </div>
    )
  }
}

// hello-world/read-video-angular/src/app/img-normalizer/img-normalizer.component.ts
import { Component, OnInit } from '@angular/core';
import { DocumentNormalizer } from '@scannerproxy/ddnjs';

@Component({
  selector: 'app-img-normalizer',
  templateUrl: './img-normalizer.component.html',
  styleUrls: ['./img-normalizer.component.css']
})
export class ImgNormalizerComponent implements OnInit {
  pNormalizer = null;

  async ngOnInit(): Promise<void> {}

  normalizeImg = async (e: any) => {
    try {
      const normalizer = await (this.pNormalizer = this.pNormalizer || DocumentNormalizer.createInstance());
      const results = await normalizer.detectQuad(e.target.files[0]);
      document.querySelector(".img-normalize-result").innerHTML = "";
      for(let item of results) {
        const norRes = await normalizer.normalize(e.target.files[0], {quad: item.location});
        const cvs = norRes.image.toCanvas();
        if(document.body.clientWidth < 600) {
          cvs.style.width = "100%";
        }
        document.querySelector(".img-normalize-result").appendChild(cvs);
      }
      console.log(results);
    } catch (ex: any) {
      let errMsg: string;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message||ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
    e.target.value = '';
  }

  async ngOnDestroy() {
    if (this.pNormalizer) {
      (await this.pNormalizer).dispose();
      this.pNormalizer = null;
      console.log('ImgNormalizer Component Unmount');
    }
  }
}

<div class="ImgParser"><input type="file" (change)="normalizeImg($event)"/></div>
<div class="img-normalized-result"></div>
