// hello-world/read-video-vue3/src/components/ImgNormalizer.vue
<template>
  <div>
    <div class="ImgNormalizer"><input type="file" ref="iptRef" @change="normalizeImg"></div>
    <div class="img-normalized-result" ref="elInr"></div>
  </div>
</template>

<script>
import { onBeforeUnmount, ref } from '@vue/runtime-core';
import { DocumentNormalizer } from "@scannerproxy/ddnjs";
export default {
  name: 'ImgNormalizer',
  setup() {
    const iptRef = ref(null);
    const elInr = ref(null);
    let pNormalizer = null;

    const normalizeImg = async (e) => {
      try {
        const normalizer = await (pNormalizer = DocumentNormalizer.createInstance());;
        let results = await normalizer.detectQuad(e.target.files[0]);
        elInr.value.innerHTML = "";
        for(let item of results) {
          const norRes = await normalizer.normalize(e.target.files[0], {quad: item.location});
          const cvs = norRes.image.toCanvas();
          if(document.body.clientWidth < 600) {
            cvs.style.width = "100%";
          }
          elInr.value.appendChild(cvs);
        }
        console.log(results);
      } catch(ex) {
        let errMsg;
        if (ex.message.includes("network connection error")) {
            errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
        } else {
            errMsg = ex.message||ex;
        }
        console.error(errMsg);
        alert(errMsg);
      }
      iptRef.value.value = '';
    }

    onBeforeUnmount(async ()=>{
      if(pNormalizer) {
        (await pNormalizer).dispose();
        pNormalizer = null;
        console.log('ImgNormalizer Component Unmount');
      }
    })

    return {
      normalizeImg,
      iptRef,
      elInr
    }
  },
}
</script>

<style scoped>
  .ImgNormalizer {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 90%;
    border: 1px solid black;
    margin-bottom: 10px;
  }
</style>

// hello-world/read-video-react/src/components/ImgNormalizer/ImgNormalizer.js
import React, { Component } from 'react';
import { DocumentNormalizer } from "@scannerproxy/ddnjs";
import './ImgNormalizer.css'

export default class ImgNormalizer extends Component {
  constructor(props) {
    super(props);
    this.pNormaelizer = null;
    this.elInr = React.createRef();
  }

  normalizeImg = async (e) => {
    try {
      const normalizer = await (this.pNormaelizer = this.pNormaelizer || DocumentNormalizer.createInstance());
      let results = await normalizer.detectQuad(e.target.files[0]);
      this.elInr.current.innerHTML = "";
      for(let item of results) {
        const norRes = await normalizer.normalize(e.target.files[0], {quad: item.location});
        const cvs = norRes.image.toCanvas();
        if(document.body.clientWidth < 600) {
          cvs.style.width = "100%";
        }
        this.elInr.current.appendChild(cvs);
      }
      console.log(results);
    } catch(ex) {
      let errMsg;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message||ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
    e.target.value = '';
  }

  async componentWillUnmount() {
    if (this.pNormalizer) {
      (await this.pNormalizer).dispose();
      this.pNormalizer = null;
      console.log('ImgNormalizer Component Unmount');
    }
  }

  render() {
    return (
      <div>
        <div className="ImgNormalizer"><input type="file" onChange={this.normalizeImg}/></div>
        <div className="img-normalized-result" ref={this.elInr}></div>
      </div>
    )
  }
}
