// hello-world/read-video-angular/src/app/hello-world/hello-world.component.ts
import { Component, OnInit } from '@angular/core';
import "../dce"; // import side effects. engineResourcePath, so on.
import '../ddn'; // import side effects. The license, engineResourcePath, so on.
import { DocumentNormalizer } from '@scannerproxy/ddnjs';

@Component({
  selector: 'app-hello-world',
  templateUrl: './hello-world.component.html',
  styleUrls: ['./hello-world.component.css']
})
export class HelloWorldComponent implements OnInit {
  bShowVideoNormalizer = true;
  async ngOnInit(): Promise<void> {
    // Load the library on page load to speed things up.
    try {
      DocumentNormalizer.loadWasm();
    } catch (ex) {
      let errMsg: string;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message||ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
  }
  swtchVideoOrImgNormalizer(): void {
    this.bShowVideoNormalizer = !this.bShowVideoNormalizer;
  }
}

<div class="helloWorld">
    <h1>Hello World for Angular<img style="height: 25px;" alt="logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
        />
    </h1>
    <div class="btn-group">
      <button [ngStyle]="{'margin-right': '5px', 'background-color': bShowVideoNormalizer ? 'rgb(255,174,55)' : 'white'}" (click)="swtchVideoOrImgNormalizer()">Video Normalizer</button>
      <button [ngStyle]="{'margin-right': '5px','background-color': !bShowVideoNormalizer ? 'rgb(255,174,55)' : 'white'}" (click)="swtchVideoOrImgNormalizer()">Image Normalizer</button>
    </div>
    <div class="container">
      <app-video-normalizer *ngIf="bShowVideoNormalizer"></app-video-normalizer>
      <app-img-normalizer *ngIf="!bShowVideoNormalizer"></app-img-normalizer>
    </div>
</div>

// hello-world/read-video-react/src/components/HelloWorld/HelloWorld.js
import React from 'react';
import './HelloWorld.css';
import reactLogo from '../../logo.svg';
import "../../dce"; // import side effects. engineResourcePath, so on.
import "../../ddn"; // import side effects. The license, engineResourcePath, so on.
import { DocumentNormalizer } from "@scannerproxy/ddnjs";
import VideoNormalizer from '../VideoNormalizer/VideoNormalizer';
import ImgNormalizer from '../ImgNormalizer/ImgNormalizer';

class HelloWorld extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            bShowVideoNormalizer: true
        };
    }
    async componentDidMount() {
        try {
            DocumentNormalizer.loadWasm();
        } catch (ex) {
            let errMsg;
            if (ex.message.includes("network connection error")) {
                errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
            } else {
                errMsg = ex.message||ex;
            }
            console.error(errMsg);
            alert(errMsg);
        }
    }

    showVideoNormalizer = () => {
        this.setState({
            bShowVideoNormalizer: !this.state.bShowVideoNormalizer,
        });
    }
    
    render() {
        return (
            <div className="helloWorld">
                <h1>Hello World for React<img src={reactLogo} className="App-logo" alt="logo" /></h1>
                <div className="btn-group">
                    <button style={{marginRight: '5px', backgroundColor: this.state.bShowVideoNormalizer ? 'rgb(255,174,55)' : 'white'}} onClick={this.showVideoNormalizer}>Video Normalizer</button>
                    <button style={{marginRight: '5px', backgroundColor: !this.state.bShowVideoNormalizer ? 'rgb(255,174,55)' : 'white'}} onClick={this.showVideoNormalizer}>Image Normalizer</button>
                </div>
                <div className="container">
                    {this.state.bShowVideoNormalizer ? (<VideoNormalizer></VideoNormalizer>) : ""}
                    {!this.state.bShowVideoNormalizer ? (<ImgNormalizer></ImgNormalizer>) : ""}
                </div>
            </div>
        );
    }
}
export default HelloWorld;
