// hello-world/read-video-vue3/src/components/ImageNormalizer.vue
<script setup lang="ts">
import { type NormalizedImageResultItem } from "@dynamsoft/ddnjs";
import { CaptureVisionRouter } from "@dynamsoft/cvrjs";
import { onMounted, onUnmounted, ref, type Ref } from "vue";

const iptRef: Ref<HTMLInputElement | null> = ref(null);
const elInr: Ref<HTMLDivElement | null> = ref(null);
const router: Ref<Promise<CaptureVisionRouter> | null> = ref(null);

onMounted(() => {
    router.value = CaptureVisionRouter.createInstance();
})

onUnmounted(async () => {
    (await router.value)!.dispose();
    console.log('ImageNormalizer Component Unmount');
})

const captureImg = async (e: any) => {
    try {
        elInr.value!.innerHTML = "";
        const normalizer = await router.value;
        const results = await normalizer!.capture(e.target.files[0], "detect-and-normalize-document");
        if(results.items.length) {
            const cvs = (results.items[0] as NormalizedImageResultItem).toCanvas();
            if (document.body.clientWidth < 600) {
                cvs.style.width = "90%";
            }
            elInr.value!.append(cvs);
        }
        console.log(results);
    } catch (ex: any) {
        let errMsg: string;
        if (ex.message.includes("network connection error")) {
            errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
        } else {
            errMsg = ex.message || ex;
        }
        console.error(errMsg);
        alert(errMsg);
    }
}
</script>

<template>
    <div class="recognize-img">
        <div class="img-ipt"><input type="file" ref="iptRef" @change="captureImg" /></div>
    </div>
    <div class="img-normalized-result" ref="elInr"></div>
</template>
    
<style scoped>
.recognize-img {
    width: 100%;
    height: 100%;
    font-family: Consolas, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace;
}

.recognize-img .img-ipt {
    width: 80%;
    height: 100%;
    display: flex;
    justify-content: center;
    border: 1px solid black;
    margin: 0 auto;
}
</style>

// hello-world/read-video-angular/src/app/image-normalizer/image-normalizer.component.ts
import { Component, ViewChild } from '@angular/core';
import { type NormalizedImageResultItem } from "@dynamsoft/ddnjs";
import { CaptureVisionRouter } from "@dynamsoft/cvrjs";

@Component({
  selector: 'app-image-normalizer',
  templateUrl: './image-normalizer.component.html',
  styleUrls: ['./image-normalizer.component.css']
})
export class ImageNormalizerComponent {
  router: Promise<CaptureVisionRouter> | null = null;

  @ViewChild('elInr') elInr: any;

  ngOnInit(): void {
    this.router = CaptureVisionRouter.createInstance();
  }

  captureImg = async (e: any) => {
    try {
      this.elInr.nativeElement!.innerHTML = "";
      const normalizer = await this.router;
      const results = await normalizer!.capture(e.target.files[0], "detect-and-normalize-document");
      if (results.items.length) {
        const cvs = (results.items[0] as NormalizedImageResultItem).toCanvas();
        if (document.body.clientWidth < 600) {
          cvs.style.width = "90%";
        }
        this.elInr.nativeElement!.append(cvs);
      }
      console.log(results);
    } catch (ex: any) {
      let errMsg: string;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message || ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
  }

  async ngOnDestroy() {
    (await this.router)!.dispose();
    console.log('ImageNormalizer Component Unmount');
  }
}
