// hello-world/read-video-vue3/src/components/HelloWorld.vue
<template>
  <div className="helloWorld">
    <h1>{{ msg }} <img class="applogo" alt="Vue logo" src="../assets/logo.png" /></h1>
    <div className="btn-group" v-if="libLoaded">
        <button :style="{marginRight: '5px', backgroundColor: bShowVideoNormalizer ? 'rgb(255,174,55)' : 'white'}" @click="showVideoNormalizer">Video Recognizer</button>
        <button :style="{marginRight: '5px', backgroundColor: bShowImgNormalizer ? 'rgb(255,174,55)' : 'white'}" @click="showImgNormalizer">Image Recognizer</button>
    </div>
    <div class="container">
      <span style="font-size: x-large" v-if="!libLoaded">Loading Library...</span>
      <VideoNormalizer v-if="bShowVideoNormalizer"></VideoNormalizer>
      <ImgNormalizer v-if="bShowImgNormalizer"></ImgNormalizer>
    </div>
  </div>
</template>

<script>
import VideoNormalizer from "./VideoNormalizer";
import ImgNormalizer from './ImgNormalizer.vue'
import { ref, onMounted } from "vue";
import { DocumentNormalizer } from "shen-dynamsoft-document-normalizer";

export default {
  name: "HelloWorld",
  props: {
    msg: String,
  },
  setup() {
    const libLoaded = ref(false);
    const bShowVideoNormalizer = ref(true);
    const bShowImgNormalizer = ref(false);
    onMounted(async () => {
      try {
        //Load the library on page load to speed things up.
        await DocumentNormalizer.loadWasm();
        libLoaded.value = true;
        showVideoNormalizer();
      } catch (ex) {
        let errMsg;
        if (ex.message.includes("network connection error")) {
          errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
        } else {
          errMsg = ex.message||ex;
        }
        console.error(errMsg);
        alert(errMsg);
      }
    });
    const showVideoNormalizer = () => {
      bShowVideoNormalizer.value = true;
      bShowImgNormalizer.value = false;
    };
    const showImgNormalizer = () => {
      bShowVideoNormalizer.value = false;
      bShowImgNormalizer.value = true;
    }
    
    return {
      libLoaded,
      bShowVideoNormalizer,
      bShowImgNormalizer,
      showVideoNormalizer,
      showImgNormalizer
    };
  },
  components: {
    VideoNormalizer,ImgNormalizer
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.container {
  margin: 2vmin auto;
  text-align: center;
  font-size: medium;
  height: 80%;
  width: 80vw;
}
.applogo {
  height: 25px;
}
.btn-group {
  width: 100%;
  text-align: center;
}
button {
  font-size: 1.5rem;
  margin: 1.5vh 0;
  border: 1px solid black;
  background-color: white;
  color: black;
}
.helloWorld {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  width: 100%;
  height: 100%;
  color: #455a64;
}

h1 {
  font-size: 1.5em;
}
</style>

// hello-world/read-video-angular/src/app/hello-world/hello-world.component.ts
import { Component, OnInit } from '@angular/core';
import "../dce"; // import side effects. engineResourcePath, so on.
import '../ddn'; // import side effects. The license, engineResourcePath, so on.
import { DocumentNormalizer } from 'shen-dynamsoft-document-normalizer';

@Component({
  selector: 'app-hello-world',
  templateUrl: './hello-world.component.html',
  styleUrls: ['./hello-world.component.css']
})
export class HelloWorldComponent implements OnInit {
  bShowVideoNormalizer = true;
  bShowImgNormalizer = false;
  async ngOnInit(): Promise<void> {
    // Load the library on page load to speed things up.
    try {
      await DocumentNormalizer.loadWasm();
    } catch (ex) {
      let errMsg: string;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message||ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
  }
  showVideoNormalizer(): void {
    this.bShowVideoNormalizer = true;
    this.bShowImgNormalizer = false;
  }
  showImgNormalizer(): void {
    this.bShowVideoNormalizer = false;
    this.bShowImgNormalizer = true;
  }
}

<div class="helloWorld">
    <h1>Hello World for Angular<img style="height: 25px;" alt="logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
        />
    </h1>
    <div class="btn-group">
        <button [ngStyle]="{'margin-right': '5px', 'background-color': bShowVideoNormalizer ? 'rgb(255,174,55)' : 'white'}" (click)="showVideoNormalizer()">Video Normalizer</button>
        <button [ngStyle]="{'margin-right': '5px','background-color': !bShowVideoNormalizer ? 'rgb(255,174,55)' : 'white'}" (click)="showImgNormalizer()">Image Normalizer</button>
    </div>
    <div class="container">
        <app-video-normalizer *ngIf="bShowVideoNormalizer"></app-video-normalizer>
        <app-img-normalizer *ngIf="bShowImgNormalizer"></app-img-normalizer>
    </div>
</div>
